services:
  mongodb:
    image: mongo:8.0.6-noble
    container_name: mongodb
    ports:
      - "27007:27017"
    volumes:
      - mongodata:/data/db
    
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

    networks:
      - backend
    restart: always

  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: ollama
  #   ports:
  #     - "11434:11434"
  #   networks:
  #     - backend
  #   restart: always

networks:
  backend:

volumes:
  mongodata:

   
